### ISSUE TITLE
0.11.0: `beartype` is not exported from module `beartype`

### ISSUE THREAD

**Issue by rsokl** [beartype/beartype#169]
![image](https://user-images.githubusercontent.com/29104956/190938305-0e99ac95-f934-4867-8d17-917a5589c09d.png)

**Comment by leycec** [comment]
**Gah!** Resolved by 305d73792de in a jiffy. You're absolutely right – as always. The fix was thankfully trivial, but colour me disappointed that neither mypy nor pyright complain when pointed at the actual @beartype codebase; they only complain when pointed at a downstream project importing from @beartype. I should probably improve integration tests to cover this and similar edge cases, but... I'll probably just end up playing video games compulsively instead. :smile: 

Thanks so much for the rapid heads-up, @rsokl. We'll kick out a new `beartype 0.11.1` patch release resolving this and more in a day or two. Until then, would you mind verifying this resolution on your end by updating to this `git` commit via:

```bash
pip3 install git+https://github.com/beartype/beartype.git@305d73792de59d8f9918fabaab76203402ddb8c6
```

**Comment by KyleKing** [comment]
I'm still getting this error with `beartype` 0.11.0 when working with the `pyright` CLI (installed with `pipx install pyright`). Below is a minimum project that I could use to replicate the issue:

```sh
~/Developer/Local/test-pyright  > pyright                                                                                                  
No configuration file found.
pyproject.toml file found at /Users/kyleking/Developer/Local/test-pyright.
Loading pyproject.toml file at /Users/kyleking/Developer/Local/test-pyright/pyproject.toml
Assuming Python version 3.10
Assuming Python platform Darwin
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /Users/kyleking/Developer/Local/test-pyright/typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.287
/Users/kyleking/Developer/Local/test-pyright/test_pyright/__init__.py
  /Users/kyleking/Developer/Local/test-pyright/test_pyright/__init__.py:2:22 - error: "beartype" is not exported from module "beartype"
    Import from "beartype._decor.decormain" instead (reportPrivateImportUsage)
1 error, 0 warnings, 0 informations 
Completed in 1.844sec 

~/Developer/Local/test-pyright  (1)  pyright --version                                                                                    
pyright 1.1.287  
~/Developer/Local/test-pyright   > tree                                                                                               
.
├── README.md
├── poetry.lock
├── pyproject.toml
├── test_pyright
│   └── __init__.py
└── tests
    └── __init__.py

2 directories, 5 files 
~/Developer/Local/test-pyright  > bat pyproject.toml                                                                                       
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: pyproject.toml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [tool.poetry]
   2   │ name = "test-pyright"
   3   │ version = "0.1.0"
   4   │ description = ""
   5   │ authors = ["Kyle King <KyleKing@users.noreply.github.com>"]
   6   │ readme = "README.md"
   7   │ packages = [{include = "test_pyright"}]
   8   │ 
   9   │ [tool.poetry.dependencies]
  10   │ python = "^3.10"
  11   │ beartype = "^0.11.0"
  12   │ pandas = "^1.5.2"
  13   │ 
  14   │ [build-system]
  15   │ requires = ["poetry-core"]
  16   │ build-backend = "poetry.core.masonry.api"
  17   │ 
  18   │ [tool.pyright]
  19   │ venvPath = "."
  20   │ venv = ".venv"
  21   │ include = "test_pyright"
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
~/Developer/Local/test-pyright  > bat test_pyright/__init__.py
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: test_pyright/__init__.py
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ import pandas as pd
   2   │ from beartype import beartype
   3   │ 
   4   │ 
   5   │ @beartype
   6   │ def hello() -> pd.DataFrame:
   7   │     return pd.DataFrame()
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
~/Developer/Local/test-pyright  >   
```

This is also a problem when running with pyright installed in the local environment as well:

```sh
> poetry add pyright --group=dev
...
> poetry run pyright
No configuration file found.
pyproject.toml file found at /Users/kyleking/Developer/Local/test-pyright.
Loading pyproject.toml file at /Users/kyleking/Developer/Local/test-pyright/pyproject.toml
Config "include" entry must must contain an array.
Assuming Python version 3.10
Assuming Python platform Darwin
No include entries specified; assuming /Users/kyleking/Developer/Local/test-pyright
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath /Users/kyleking/Developer/Local/test-pyright/typings is not a valid directory.
Searching for source files
Found 2 source files
pyright 1.1.287
/Users/kyleking/Developer/Local/test-pyright/test_pyright/__init__.py
  /Users/kyleking/Developer/Local/test-pyright/test_pyright/__init__.py:2:22 - error: "beartype" is not exported from module "beartype"
    Import from "beartype._decor.decormain" instead (reportPrivateImportUsage)
1 error, 0 warnings, 0 informations 
Completed in 0.984sec 
```

**Comment by KyleKing** [comment]
There's a lot of magic in the `setup.py` that goes over my head 😄, but this could just be an error on my part for configuring `pyright`? Although `pyright` does recognize `pandas`

**Comment by leycec** [comment]
**Gah!** So much profuse apologies, @KyleKing. This is entirely on me and my sluggishness. I'm like a slug-cat that somehow miraculously codes despite a torpid metabolism and lack of hands. <sup>:snail: + :cat: = @leycec</sup>

I fixed this only a day after releasing `beartype 0.11.0`. Then I failed to push out a new stable release. When wonderful users such as yourself begin loudly face-planting into supposedly fixed things, I know it's time to excrete a new release.

Thanks a heap for realigning me with physical reality. I need the occasional swift kick like this to actually achieve real-world goals. I am now sighing. :face_exhaling:
